//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostava
    {
        public string RestId { get; set; }
        public string KvartId { get; set; }
        public int PostBroj { get; set; }
        public Nullable<int> vrijeme { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual Kvart Kvart { get; set; }
        public virtual Kvart Kvart1 { get; set; }
        public virtual Restoran Restoran { get; set; }
    }
}
