//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FDBContext : DbContext
    {
        public FDBContext()
            : base("name=FDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DnevniMeni> DnevniMeni { get; set; }
        public virtual DbSet<Dostava> Dostava { get; set; }
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Kvart> Kvart { get; set; }
        public virtual DbSet<Meni> Meni { get; set; }
        public virtual DbSet<Narudba> Narudba { get; set; }
        public virtual DbSet<RadnoVrijeme> RadnoVrijeme { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Restoran> Restoran { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vlasnik> Vlasnik { get; set; }
        public virtual DbSet<Zupanija> Zupanija { get; set; }
    }
}
