//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class JelaUMeniju
    {
        public string RestId { get; set; }
        public string JeloId { get; set; }
        [Required(ErrorMessage = "Upišite cijenu jela!")]
        public Nullable<decimal> cijena { get; set; }
        [Required(ErrorMessage = "Upišite ime jela!")]
        public string ImeJela { get; set; }
        [Required(ErrorMessage = "Upišite opis jela!")]
        public string OpisJela { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
