//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meni
    {
        public string MeniId { get; set; }
        public string JelaId { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public string ImeJela { get; set; }
        public string OpisJela { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
