//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Narudba
    {
        public int NarId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> Telefon { get; set; }
        public string Grad { get; set; }
        public string ImeKvarta { get; set; }
        public string Ulica { get; set; }
        public string KucniBroj { get; set; }
        public string OIB { get; set; }
        public string RestId { get; set; }
        public string email { get; set; }
        public string ImeJela { get; set; }
        public Nullable<decimal> cijena { get; set; }
        public Nullable<System.TimeSpan> vrijeme { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
