//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RadnoVrijeme
    {
        public string RestId { get; set; }
        public string Dan { get; set; }
        public Nullable<System.TimeSpan> VrijemeOd { get; set; }
        public Nullable<System.TimeSpan> VrijemeDo { get; set; }
        public string StatusRada { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
