//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public string RestId { get; set; }
        public Nullable<int> jedna { get; set; }
        public Nullable<int> dvije { get; set; }
        public Nullable<int> tri { get; set; }
        public Nullable<int> cetiri { get; set; }
        public Nullable<int> pet { get; set; }
    
        public virtual Restoran Restoran { get; set; }
    }
}
