//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IamHungry.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Restoran
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Restoran()
        {
            this.DnevniMeni = new HashSet<DnevniMeni>();
            this.Dostava = new HashSet<Dostava>();
            this.Meni = new HashSet<Meni>();
            this.Narudba = new HashSet<Narudba>();
            this.RadnoVrijeme = new HashSet<RadnoVrijeme>();
            this.Vlasnik = new HashSet<Vlasnik>();
        }
    
        public string RestId { get; set; }
        public string ImeRest { get; set; }
        public Nullable<int> PostBroj { get; set; }
        public string Ulica { get; set; }
        public string KvartId { get; set; }
        public string MeniId { get; set; }
        public string email { get; set; }
        public string Passw { get; set; }
        public string KucniBroj { get; set; }
        public Nullable<int> Telefon { get; set; }
        public Nullable<int> Mobitel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DnevniMeni> DnevniMeni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostava> Dostava { get; set; }
        public virtual Grad Grad { get; set; }
        public virtual Kvart Kvart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Meni> Meni { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Narudba> Narudba { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RadnoVrijeme> RadnoVrijeme { get; set; }
        public virtual Rating Rating { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vlasnik> Vlasnik { get; set; }
    }
}
